export type TOmittedConnectedFormProps<T extends Record<string, any>> = Omit<
  T,
  (typeof omittedPropsConnectedForm)[number]
>;

export const omittedPropsConnectedForm = [
  "component",
  "onKeyDown",
  "isFeatureEnabled",
  "localization",
  "form",
  "formName",
  "onFormUnmount",
  "setFormData",
  "sortByPriority",
  "userConfirmationProvider",
  "blockUri",
  "accessKeys",

  "active",
  "dirty",
  "dirtyFields",
  "dirtyFieldsSinceLastSubmit",
  "dirtySinceLastSubmit",
  "errors",
  "hasSubmitErrors",
  "hasValidationErrors",
  "initialValues",
  "invalid",
  "modified",
  "modifiedSinceLastSubmit",
  "pristine",
  "submitErrors",
  "submitFailed",
  "submitSucceeded",
  "submitting",
  "touched",
  "valid",
  "validating",
  "values",
  "visited",
  "handleSubmit",
  "__versions",
] as const;
